### ISSUE TITLE
Basic Principled Shader support in FBX export

### ISSUE THREAD

**Issue by DoctorWhoof** [sideeffects/HoudiniFBX#3]
Hi,

It would be incredibly helpful if Principled shaders exported correctly to FBX, even if just the most basic parameters (i.e. color and color texture).

Currently it seems to export empty materials when it encounters a Principled shader, which is causing all sorts of trouble on my end.

Thanks!

**Comment by dpernuit** [comment]
Hi,
Support for PrincipledShaders has been added to FBX (import and export) in recent version of Houdini (17.5)
