### ISSUE TITLE
Another Compilation problem

### ISSUE THREAD

**Issue by matko7274** [sideeffects/HoudiniFBX#7]
Hi, i downloaded latest version of VS2017 and cygwin to compile the ROP, everything was fine until i did make ROP_FBX.dll in the ROP folder. It didnt compile and it reported this:

Makefile:47: /toolkit/makefiles/Makefile.gnu: No such file or directory 
make *** No rule to make target "/toolkit/makefiles/Makefile.gnu". Stop.

My MSVCDir path is "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023"

Did i set my MSVCDir path incorrectly or is the problem somewhere else ? 

Kind Regards
Martin

**Comment by e4lam** [comment]
That error seems to suggest that you don't have the HFS environment variable set. Building anything with the devkit assumes that you started it from the Houdini Command Line Tools which sets up various environment variables.

**Comment by matko7274** [comment]
Ok, i made some progress, I set my HFS variable and tried make ROP_FBX.dll which reported this error:

==== Building for Houdini 18.5.633 ====
make: *** No rule to make target 'ROP_FBX.dll'.  Stop.

Then i tried only plain make without any other arguments in the ROP directory, and i made some progress and then it stopped with this error:

==== Building for Houdini 18.5.633 ====
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023/bin/Hostx64/x64/cl" -c -nologo -TP -Zc:forScope -Zc:rvalueCast -Zc:inline -Zc:strictStrings -std:c++14 -Zc:referenceBinding -Zc:ternary -Zc:throwingNew -permissive- -Zc:__cplusplus -DAMD64 -DSIZEOF_VOID_P=8 -DI386 -DWIN32 -DSWAP_BITFIELDS -D_WIN32_WINNT=0x0600 -DNOMINMAX -DSTRICT -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DSESI_LITTLE_ENDIAN -DHBOOST_ALL_NO_LIB -DEIGEN_MALLOC_ALREADY_ALIGNED=0 -DFBX_ENABLED=1 -DOPENCL_ENABLED=1 -DOPENVDB_ENABLED=1 -I . -IE:\Houdini/toolkit/include -IE:\Houdini/toolkit/include/fbx -I "E:\Houdini/toolkit/include" -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023/include" -I "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -I "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -I "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -wd4355 -w14996 -O2 -DNDEBUG -MD -EHsc -GR -bigobj  -DMAKING_DSO \
    ROP_FBX.C -FoROP_FBX.o
ROP_FBX.C
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023/include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
make: *** [E:\Houdini/toolkit/makefiles/Makefile.gnu:71: ROP_FBX.o] Error 2

I dont know what is wrong, when i set my HFS variable which is E:\Houdini and my MSVCDir variable.

**Comment by matko7274** [comment]
And one small thing to note, after i set HFS variable, Houdini Apprentice refused to open, resulting in dll load failed: Zadan.

**Comment by e4lam** [comment]
It's trying to look for `C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt/corecrt.h` but it can't find it. My guess is that you don't have that particular Windows SDK version installed? You might need to modify `%HFS%\toolkit\makefiles\Makefile.win` in that case and adjust the value for `WIN32_KIT` and/or `WIN32_KIT_VERSION` appropriately.

**Comment by matko7274** [comment]
Thank you, i downloaded the Windows SDK and modified the WIN32_KIT_VERSION variable in the Makefile.win and with plain make it compiled !

**Comment by matko7274** [comment]
I will close this since i solved the problem.
